<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dc649858-0a0f-4475-81d7-653c2db83c84</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.20" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FuelLoyalty.Contracts\FuelLoyalty.Contracts.csproj" />
    <ProjectReference Include="..\FuelLoyalty.ServiceDefaults\FuelLoyalty.ServiceDefaults.csproj" />
    <ProjectReference Include="..\FuelLoyalty.SharedKernel\FuelLoyalty.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\Persistence\Migrations\" />
  </ItemGroup>

</Project>
